<a href="https://colab.research.google.com/github/nrussell93/prework-about-me/blob/master/Machine_Learning_Homework_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [189]:
# HW_5 Problem 1

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from google.colab import drive
drive.mount('/content/drive')

file_path = '/content/drive/My Drive/Colab Notebooks/diabetes.csv'
diabetes = pd.DataFrame(pd.read_csv(file_path))
diabetes.head()
diabetes.shape
diabetes[5:]
#Shape (768,9)

X = diabetes.iloc[:,[0,1,2,3,4,5,6,7]]
Y = diabetes.iloc[:,8]


# Split dataset into training and  test set
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size = 0.20, random_state = 0)


# Normalize all inputs
from sklearn.preprocessing import MinMaxScaler
scale_diabetes = MinMaxScaler()
X_train = scale_diabetes.fit_transform(X_train)
X_test = scale_diabetes.fit_transform(X_test)

# Standardize all inputs
from sklearn.preprocessing import StandardScaler
stand_diabetes = StandardScaler()
X_train = stand_diabetes.fit_transform(X_train)
X_test = stand_diabetes.fit_transform(X_test)

# Begin regression
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train,Y_train)

Y_pred = classifier.predict(X_test)


# Use confusion matrix to get accuracy of the model
from sklearn.metrics import confusion_matrix
cnf_matrix = confusion_matrix(Y_test,Y_pred)


from sklearn import metrics
print("Accuracy:",metrics.accuracy_score(Y_test, Y_pred))
print("Precision:",metrics.precision_score(Y_test, Y_pred))
print("Recall:",metrics.recall_score(Y_test, Y_pred))
print("F1 Score: ",metrics.f1_score(Y_test, Y_pred))

cnf_matrix




Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Accuracy: 0.7987012987012987
Precision: 0.6904761904761905
Recall: 0.6170212765957447
F1 Score:  0.651685393258427


array([[94, 13],
       [18, 29]])

In [203]:
# Problem 2

file_path = '/content/drive/My Drive/Colab Notebooks/cancer.csv'
cancer = pd.DataFrame(pd.read_csv(file_path))
cancer.head()
cancer.shape
cancer[5:]

X = cancer.iloc[:,[2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31]]
Y = cancer.iloc[:,1]

# Convert M and B diagnosis into 0 and 1
var_list =  ['diagnosis']

# Convert M and B diagnosis into 0 and 1
def data_map(y):
    return y.map({'M': 1, 'B': 0})
cancer[var_list] = cancer[var_list].apply(data_map)
cancer.head()

# Seperate cancer dataset into training set and validation set
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size = 0.20, random_state = 0)

# Normalize the parameters within the entire cancer dataset
from sklearn.preprocessing import MinMaxScaler
scale_cancer = MinMaxScaler()
X_train = scale_cancer.fit_transform(X_train)
X_test = scale_cancer.fit_transform(X_test)
X_train[5:]

# Standardize inputs
from sklearn.preprocessing import StandardScaler
stand_cancer = StandardScaler()
X_train = stand_cancer.fit_transform(X_train)
X_test = stand_cancer.fit_transform(X_test)
X_train[5:]

# Begin regression
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression()
classifier.fit(X_train,Y_train)

# Apply the Logistic classification model to the validation set
Y_pred = classifier.predict(X_test)
Y_pred[0:9]

# Use confusion matrix to get accuracy of the model
from sklearn.metrics import confusion_matrix
cnf_matrix = confusion_matrix(Y_test,Y_pred)
cnf_matrix

from sklearn import metrics
print("Accuracy:",metrics.accuracy_score(Y_test, Y_pred))
print("Precision:",metrics.precision_score(Y_test, Y_pred, pos_label = 'M'))
print("Recall:",metrics.recall_score(Y_test, Y_pred, pos_label = 'M'))
print("F1 Score: ",metrics.f1_score(Y_test, Y_pred, pos_label = 'M'))
display(cnf_matrix)

# Problem 1, part B
classifier_penalty = LogisticRegression(penalty= 'l2',max_iter=1000, random_state=0)
classifier_penalty.fit(X_train,Y_train)

y_pred = classifier_penalty.predict(X_test)

from sklearn.metrics import confusion_matrix
cnf_matrix = confusion_matrix(Y_test,y_pred)
cnf_matrix

from sklearn import metrics
print("Accuracy_weighted:",metrics.accuracy_score(Y_test, y_pred))
print("Precision_weighted:",metrics.precision_score(Y_test, y_pred, pos_label = 'M'))
print("Recall_weighted:",metrics.recall_score(Y_test, y_pred, pos_label = 'M'))
print("F1 Score_weighted: ",metrics.f1_score(Y_test, y_pred, pos_label = 'M'))
cnf_matrix

Accuracy: 0.956140350877193
Precision: 0.9565217391304348
Recall: 0.9361702127659575
F1 Score:  0.9462365591397849


array([[65,  2],
       [ 3, 44]])

Accuracy_weighted: 0.956140350877193
Precision_weighted: 0.9565217391304348
Recall_weighted: 0.9361702127659575
F1 Score_weighted:  0.9462365591397849


array([[65,  2],
       [ 3, 44]])

In [207]:
# Problem 3
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import datasets
from sklearn.datasets import load_iris
from sklearn.naive_bayes import GaussianNB
file_path = '/content/drive/My Drive/Colab Notebooks/cancer.csv'
cancer = pd.DataFrame(pd.read_csv(file_path))
cancer.head()
cancer.shape
cancer[5:]

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn import metrics

# Load the cancer dataset (replace with your correct file path)
file_path = '/content/drive/My Drive/Colab Notebooks/cancer.csv'
cancer = pd.read_csv(file_path)

# Assuming your target column is named 'diagnosis' (M or B)
X = cancer.iloc[:, 2:31]  # Select the features
Y = cancer['diagnosis'].map({'M': 1, 'B': 0})  # Map labels to 1 and 0

# Split the data into training and test sets
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.20, random_state=0)



# Fit a Naive Bayes model to the data
model = GaussianNB()
model.fit(X_train, Y_train)


# Make predictions on the test data
predicted = model.predict(X_test)

# Print results
from sklearn import metrics
print(metrics.classification_report(Y_test, predicted))
print(metrics.confusion_matrix(Y_test, predicted))


              precision    recall  f1-score   support

           0       0.94      0.94      0.94        67
           1       0.91      0.91      0.91        47

    accuracy                           0.93       114
   macro avg       0.93      0.93      0.93       114
weighted avg       0.93      0.93      0.93       114

[[63  4]
 [ 4 43]]


In [211]:
# Problem 4
import numpy as np
import pandas as pd
from sklearn import datasets
from sklearn.datasets import load_iris
from sklearn.naive_bayes import GaussianNB
import seaborn as sns
from sklearn.cluster import KMeans
from sklearn.cluster import SpectralClustering
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
from sklearn.preprocessing import StandardScaler


file_path = '/content/drive/My Drive/Colab Notebooks/cancer.csv'
cancer = pd.DataFrame(pd.read_csv(file_path))
cancer_new = pd.DataFrame(cancer)
#cancer_new = cancer_new.dropna()

# standard = StandardScaler()
# X_train = standard.fit_transform(X_train)
# X_test = standard.transform(X_test)

#accur = 0
#a_array = []

best_accuracy = 0
best_k = 0

for k in range(1, 30):
    X_training, X_testing = pcaReduction(X_train, X_test, k)

    # Increase max_iter to 1000 for logistic regression
    classifier_pca = LogisticRegression(random_state=0, max_iter=1000)
    classifier_pca.fit(X_training, Y_train)
    Y_predict = classifier_pca.predict(X_testing)

    accuracy = metrics.accuracy_score(Y_test, Y_predict)

    a_array.append(accuracy)

    if accuracy > best_accuracy:
        best_accuracy = accuracy
        best_k = k

print("Optimal K value: ", best_k)
print("Most Accuracy: ", best_accuracy)

classifier_optimal = LogisticRegression(random_state=0, max_iter=1000)
X_training, X_testing = pcaReduction(X_train, X_test, best_k)
classifier_optimal.fit(X_training, Y_train)
Y_prediction = classifier_optimal.predict(X_testing)

# Print results
print(metrics.classification_report(Y_test, Y_prediction))
print(metrics.confusion_matrix(Y_test, Y_prediction))


Optimal K value:  1
Most Accuracy:  0.9122807017543859
              precision    recall  f1-score   support

           0       0.90      0.96      0.93        67
           1       0.93      0.85      0.89        47

    accuracy                           0.91       114
   macro avg       0.92      0.90      0.91       114
weighted avg       0.91      0.91      0.91       114

[[64  3]
 [ 7 40]]


In [187]:
# Problem 5

import numpy as np
import pandas as pd
from sklearn.decomposition import PCA
from sklearn.naive_bayes import GaussianNB
from sklearn import metrics
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

# Load your dataset and preprocess it
file_path = '/content/drive/My Drive/Colab Notebooks/cancer.csv'
cancer = pd.read_csv(file_path)

# Divide up features and ideal answer
X = cancer.iloc[:, 2:31]
Y = cancer['diagnosis'].map({'M': 1, 'B': 0})

# Split the data into training and testing sets
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=0)

# Standardize the data
standard = StandardScaler()
X_train = standard.fit_transform(X_train)
X_test = standard.transform(X_test)

best_accuracy = 0
best_k = 0

for k in range(1, 30):
    # Perform PCA with k components
    pca = PCA(n_components=k)
    X_train_pca = pca.fit_transform(X_train)
    X_test_pca = pca.transform(X_test)

    # Train a Gaussian Naive Bayes classifier
    classifier_pca = GaussianNB()
    classifier_pca.fit(X_train_pca, Y_train)
    Y_predict = classifier_pca.predict(X_test_pca)

    accuracy = metrics.accuracy_score(Y_test, Y_predict)

    if accuracy > best_accuracy:
        best_accuracy = accuracy
        best_k = k

print("Optimal K value: ", best_k)
print("Most Accuracy: ", best_accuracy)

# Train the classifier with the optimal number of components
pca = PCA(n_components=best_k)
X_train_pca = pca.fit_transform(X_train)
X_test_pca = pca.transform(X_test)

classifier_optimal = GaussianNB()
classifier_optimal.fit(X_train_pca, Y_train)
Y_prediction = classifier_optimal.predict(X_test_pca)

# Print results
print(metrics.classification_report(Y_test, Y_prediction))
print(metrics.confusion_matrix(Y_test, Y_prediction))


Optimal K value:  5
Most Accuracy:  0.9298245614035088
              precision    recall  f1-score   support

           0       0.93      0.96      0.94        67
           1       0.93      0.89      0.91        47

    accuracy                           0.93       114
   macro avg       0.93      0.92      0.93       114
weighted avg       0.93      0.93      0.93       114

[[64  3]
 [ 5 42]]
